name: emilvesterberg
favicon: null
layout_spectrum: 0.5743230548687279
typography_spectrum: 0.9711437488440424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6385816950351
  lightness: 0.8703833157196641
  saturation: 0.06554570840671659
  rhythmicContrast: 0.8625449538230896
purpose: []
